---
  username:
    description: "Bitbucket username"
    type: "string"
    secret: false
    required: true
  password:
    description: "Bitbucket password"
    type: "string"
    secret: true
    required: true
  email:
    description: "Your email address"
    type: "string"
    secret: false
    required: true
  sensor:
    type: "object"
    additionalProperties: false
    properties:
      bitbucket_type:
        type: "string"
        description: "BitBucket service type"
        required: true
        enum:
          - "cloud"
          - "server"
      bitbucket_server_url:
        type: "string"
        description: "URL of BitBucket server (this is only required to set in the case of the 'bitbucket_type' is set 'server')"
        required: false
      targets:
        type: "array"
        required: true
        items:
          type: "object"
          required: true
          additionalProperties: false
          properties:
            repository:
              type: "string"
              description: "Repository name to monitor including username/project (e.g. hoge/fuga)"
              required: true
            branches:
              type: "array"
              description: "Branch name to monitor in the repository"
              default: ["master"]
              items:
                type: "string"
      timeout:
        type: "integer"
        description: "Timeout seconds for confirmation processing"
        default: 20
