---
  username:
    description: "Bitbucket username"
    type: "string"
    secret: false
    required: true
  password:
    description: "Bitbucket password"
    type: "string"
    secret: true
    required: true
  email:
    description: "Your email address"
    type: "string"
    secret: false
    required: true
  sensor:
    type: "object"
    properties:
      bitbucket_type:
        type: "string"
        description: "BitBucket service type"
        required: true
        enum:
          - "cloud"
          - "server"
      bitbucket_server_url:
        type: "string"
        description: "URL of BitBucket server (this is only required to set in the case of the 'bitbucket_type' is set 'server')"
        required: false
      repositories:
        type: "array"
        description: "Repository names to monitor including username/project (e.g. hoge/fuga)"
        required: true
