---
name: "post_receive_webhook"
pack: "bitbucket"
description: "Trigger ST2 pack deploy for commit on Git branch"
enabled: false

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "bitbucket_post_receive"

criteria:
  trigger.body:
    pattern: "changesets"
    type: "exists"

action:
  ref: "packs.install"
  parameters:
    packs:
      - "https://bitbucket.org/{{trigger.body.repository.full_name}}={{trigger.body.refChanges[0].refId}}"
