---
name: "post_receive_webhook"
pack: "bitbucket"
description: "Trigger ST2 pack deploy for commit on Git branch"
enabled: false

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "bitbucket_post_receive"

criteria:
  trigger.body:
    pattern: "changesets"
    type: "exists"

action:
  ref: "packs.deploy"
  parameters:
    auto_deploy: true
    repo_name:  "{{trigger.body.repository.name}}"
    branch:     "{{trigger.body.refChanges[0].refId}}"
    packs:      [ "{{trigger.body.repository.name}}" ]
    message:    "{{trigger.body.changesets.get('values')[0].toCommit.message}}"
    author:     "{{trigger.body.changesets.get('values')[0].toCommit.author.name}}"
